### ISSUE TITLE
Validate that P2A rules engine is executing rules correctly

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/p2a-rule-engine#8]
Rule outputs appear implausible in several cases. Create tests that validate correctness of rules engine execution.

**Comment by corviday** [comment]
Arelia noted that the projected shift from a snow-dominated watershed to a rain-dominated watershed in the Cariboo region was implausible, so I did the relevant calculations manually and got vastly different answers, indicating the rules engine was doing something off.

The problem turns out to be that the climate explorer backend, which was designed as a web interface, [expects numerical parameters to be provided to API endpoints as strings](https://github.com/pacificclimate/climate-explorer-backend/issues/135), since this is how they are received when an API endpoint is called from a URL. It behaves incorrectly when directly passed an int `0` parameter rather than the expected string `"0"` parameter to mean zero.

Short term, I resolved this by casting arguments to the `/multistats` query as string right [here](https://github.com/pacificclimate/p2a-rule-engine/blob/75f62fdb646a0503d99318024628804e950e88d5/p2a_impacts/fetch_data.py#L109); longterm we'll want the backend to be able to[ handle integer parameters correctly](https://github.com/pacificclimate/climate-explorer-backend/issues/135).
